version: '3.7'

services:
  admin:
    hostname: admin
    image: fl-node
    entrypoint: /root/admin_authorize.sh
    deploy:
      replicas: $ADMINS
    environment:
      - IPFS_API=/dns/host.docker.internal/tcp/5001
      - CONTRACT_ORACLE=$CONTRACT_ORACLE
      - ORACLE_NODE_ADDRESS=$ORACLE_NODE_ADDRESS
    volumes:
      - ../../artifacts/@chainlink/contracts/src/v0.8/operatorforwarder/dev/$ABI_FILE_ORACLE.sol/$ABI_ORACLE.json:/root/abi_operator.json

    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    external:
      name: BCFL
